### ISSUE TITLE
MCL dependency fails to build with newer version of GCC

### ISSUE THREAD

**Issue by kbipinkumar** [matsen/pplacer#389]
Thanks for getting pplacer to recent version of ocaml(#385). this has been great help in getting the tool to be built on rolling release distros like archlinux which we were not able to do earlier(#377). However, we have run into issue where the mcl dependency fails to build with recent version of gcc (15.2.1) 

The first error we encountered was this,

```log
gcc -DHAVE_CONFIG_H -I. -I../.. -I../../src -I../..    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/pplacer/src=/usr/src/debug/pplacer -flto=auto  -MT mclcm.o -MD -MP -MF .deps/mclcm.Tpo -c -o mclcm.o mclcm.c
mclcm.c:329:6: error: conflicting types for ‘usage’; have ‘void(const char **)’
  329 | void usage
      |      ^~~~~
In file included from mclcm.c:73:
../../src/mcl/procinit.h:44:6: note: previous declaration of ‘usage’ with type ‘void(void)’
   44 | void usage();
      |      ^~~~~
make[3]: *** [Makefile:270: mclcm.o] Error 1
```
It seems `procinit.h` file declares function `usage()` with no parameters, but the actual function implementation in `mclcm.c` takes a parameter `(const char **)`

we were able to fix this by applying the patch

```diff
diff --git a/src/mcl/procinit.h b/src/mcl/procinit.h
index 75b0ff6..294b406 100644
--- a/src/mcl/procinit.h
+++ b/src/mcl/procinit.h
@@ -41,7 +41,7 @@ void doBool(const char *string, mclProcParam* mp);
 int  doInfoFlag(const char *string, mclProcParam* mp);
 int  flagWithArg(const int a, const char *string);
 void toggle(int* i, const char* s);
-void usage();
+void usage(const char **);
 
 
 #endif
```
after applying this patch, we ran into the next build error

```log
gcc -DHAVE_CONFIG_H -I. -I../.. -I../../src -I../..    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/pplacer/src=/usr/src/debug/pplacer -flto=auto  -MT mcxclcf.o -MD -MP -MF .deps/mcxclcf.Tpo -c -o mcxclcf.o mcxclcf.c
mcxclcf.c: In function ‘clcfMain’:
mcxclcf.c:263:20: error: implicit declaration of function ‘mclx_set_threads_or_die’ [-Wimplicit-function-declaration]
  263 |    ;  n_thread_g = mclx_set_threads_or_die("mcx clcf", n_thread_l, i_group, n_group_G)
      |                    ^~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:393: mcxclcf.o] Error 1
```

function `mclx_set_threads_or_die()` called in `mcxclcf.c` was missing and needed to be declared by adding `impala/app.h` header to the file so that building mcl could finish successfully

```diff
diff --git a/src/shmx/mcxclcf.c b/src/shmx/mcxclcf.c
index c2c82c2..b95624e 100644
--- a/src/shmx/mcxclcf.c
+++ b/src/shmx/mcxclcf.c
@@ -33,6 +33,7 @@
 #include "impala/matrix.h"
 #include "impala/tab.h"
 #include "impala/stream.h"
+#include "impala/app.h"
 
 #include "gryphon/path.h"
 
```

**Comment by kbipinkumar** [comment]
Yes we are able to build with updated commit. Looking forward to see it in main branch.
